### https://treasurydirect.gov/BC/SBCPrice

### POST user 
POST https://treasurydirect.gov/BC/SBCPrice?RedemptionDate=03%2F2022&Series=EE&Denomination=50&SerialNumber=d54784608ee&IssueDate=10%2F1999&btnAdd.x=CALCULATE&SerialNumList=d54784608ee%3B&IssueDateList=702%3B&SeriesList=EE%3B&DenominationList=50%3B&IssuePriceList=25.00%3B&InterestList=29.14%3B&YTDInterestList=0.08%3B&ValueList=54.14%3B&InterestRateList=0.52%3B&NextAccrualDateList=972%3B&MaturityDateList=1062%3B&NoteList=+%3B&OldRedemptionDate=971&ViewPos=1&ViewType=Partial&Version=6
Content-Type: text/html

### POST user 
POST https://treasurydirect.gov/BC/SBCPrice?RedemptionDate=03%2F2022&Series=EE&Denomination=50&SerialNumber=d54784608ee&IssueDate=10%2F1999&btnAdd.x=CALCULATERedemptionDate=971&ViewPos=1&ViewType=Partial&Version=6
Content-Type: text/html


